---
title: "Posterior3"
author: "Linyi Guo"
date: "2019/11/26"
output: html_document
---

```{r include=FALSE}
rm(list=ls())
set.seed(9483)
```

```{r include=FALSE}
library(seasonal)
library(KFAS)
library(ggplot2)
library(plotly)
```

```{r include=FALSE}
Data1 <- read.csv('C:\\Users\\GuoLY\\Desktop\\markdown\\simulation&reproduction\\data\\data1.csv')
Data2 <- read.csv('C:\\Users\\GuoLY\\Desktop\\markdown\\simulation&reproduction\\data\\data2.csv')
Data3 <- read.csv('C:\\Users\\GuoLY\\Desktop\\markdown\\simulation&reproduction\\data\\data3.csv')
Data4 <- read.csv('C:\\Users\\GuoLY\\Desktop\\markdown\\simulation&reproduction\\data\\data4.csv')
Data5 <- read.csv('C:\\Users\\GuoLY\\Desktop\\markdown\\simulation&reproduction\\data\\data5.csv')
Data6 <- read.csv('C:\\Users\\GuoLY\\Desktop\\markdown\\simulation&reproduction\\data\\data6.csv')
Data7 <- read.csv('C:\\Users\\GuoLY\\Desktop\\markdown\\simulation&reproduction\\data\\data7.csv')
Data8 <- read.csv('C:\\Users\\GuoLY\\Desktop\\markdown\\simulation&reproduction\\data\\data8.csv')
Data9 <- read.csv('C:\\Users\\GuoLY\\Desktop\\markdown\\simulation&reproduction\\data\\data9.csv')
Data0 <- read.csv('C:\\Users\\GuoLY\\Desktop\\markdown\\simulation&reproduction\\data\\data0.csv')
```
```{r}
data1 <- ts(Data1[,2], start=c(2000,01), frequency=12)
data2 <- ts(Data2[,2], start=c(2000,01), frequency=12)
data3 <- ts(Data3[,2], start=c(2000,01), frequency=12)
data4 <- ts(Data4[,2], start=c(2000,01), frequency=12)
data5 <- ts(Data5[,2], start=c(2000,01), frequency=12)
data6 <- ts(Data6[,2], start=c(2000,01), frequency=12)
data7 <- ts(Data7[,2], start=c(2000,01), frequency=12)
data8 <- ts(Data8[,2], start=c(2000,01), frequency=12)
data9 <- ts(Data9[,2], start=c(2000,01), frequency=12)
data0 <- ts(Data0[,2], start=c(2000,01), frequency=12)



data1_x11 <- seas(data1, x11='')
data2_x11 <- seas(data2, x11='')
data3_x11 <- seas(data3, x11='')
data4_x11 <- seas(data4, x11='')
data5_x11 <- seas(data5, x11='')
data6_x11 <- seas(data6, x11='')
data7_x11 <- seas(data7, x11='')
data8_x11 <- seas(data8, x11='')
data9_x11 <- seas(data9, x11='')
data0_x11 <- seas(data0, x11='')
```

```{r}
Datalist <- list(data1=data1, data2=data2, data3=data3, data4=data4, data5=data5, 
                 data6=data6, data7=data7, data8=data8, data9=data9, data0=data0)
```

```{r echo=FALSE}
par(mfrow=c(2,2))
plot(data1_x11)
plot(series(data1_x11, 'd13'))
plot(series(data1_x11, 'd12'))
plot(series(data1_x11, 'd10'))

plot(data2_x11)
plot(series(data2_x11, 'd13'))
plot(series(data2_x11, 'd12'))
plot(series(data2_x11, 'd10'))

plot(data3_x11)
plot(series(data3_x11, 'd13'))
plot(series(data3_x11, 'd12'))
plot(series(data3_x11, 'd10'))

plot(data4_x11)
plot(series(data4_x11, 'd13'))
plot(series(data4_x11, 'd12'))
plot(series(data4_x11, 'd10'))

plot(data5_x11)
plot(series(data5_x11, 'd13'))
plot(series(data5_x11, 'd12'))
plot(series(data5_x11, 'd10'))

plot(data6_x11)
plot(series(data6_x11, 'd13'))
plot(series(data6_x11, 'd12'))
plot(series(data6_x11, 'd10'))

plot(data7_x11)
plot(series(data7_x11, 'd13'))
plot(series(data7_x11, 'd12'))
plot(series(data7_x11, 'd10'))

plot(data8_x11)
plot(series(data8_x11, 'd13'))
plot(series(data8_x11, 'd12'))
plot(series(data8_x11, 'd10'))

plot(data9_x11)
plot(series(data9_x11, 'd13'))
plot(series(data9_x11, 'd12'))
plot(series(data9_x11, 'd10'))

plot(data0_x11)
plot(series(data0_x11, 'd13'))
plot(series(data0_x11, 'd12'))
plot(series(data0_x11, 'd10'))
par(mfrow=c(1,1))
```


# Define another prior (prior3)

$$logPrior = -k_1*(\sigma_y^2)^2-k_2*(\sigma_T^2)^2$$

but we still choose $k1=c1*p$ and $k2=c2*p$ but this time we do a further improvement: 
$$logPrior = -c_1*p_1*(\sigma_y^2)^2-c_2*p_2*(\sigma_T^2)^2$$

where $$p_1 = -\frac{loglikelihood(15,1,1)}{15}$$
and $$p_2 = -\frac{loglikelihood(1,15,1)}{15}$$

**Note: ** loglikelihood is a negative number here so we add '-' in p's expression.


```{r}
# logprior
logprior3 <- function(sigma,c1,c2,p1,p2){
  return(-c1*p1*sigma[1]^2- c2*p2*sigma[2]^2)
}
```


BTW we give a bunch of other definations below:

```{r}
# loss
Dif1 <- function(x11, ssm, data, sigma){
  
  x11_trend <- series(x11, 'd12')
  x11_seasonal <- series(x11, 'd10')
  x11_irregular <- series(x11, 'd13')
  
  ssm_trend <- coef(ssm, states = 'trend')
  ssm_seasonal <- -rowSums(coef(ssm, states='seasonal'))
  ssm_irregular <- data[-1] - ssm_trend[-1] - ssm_seasonal[-length(data)]
 
  D <-  sum((x11_irregular[-1]-ssm_irregular)^2)/sigma[1] + 
    sum((x11_trend-ssm_trend)^2)/sigma[2] + 
    sum((x11_seasonal[-1]-ssm_seasonal[-length(data)])^2)/sigma[3] 
    
  return(D)
}



# exhaustion

exhaustion1 <- function(data){
  
  Difference <- c()
  index <- c()
  
  x11 <- seas(data, x11='')
   for (i in 1:15) {
     for (j in 1:15) {
         
           ssmm <- SSModel(data ~ SSMtrend(1, Q=list(j)) + 
                     SSMseasonal(12, sea.type = 'dummy', Q = 1),
                   H = i)
           ssm <- KFS(ssmm)
           
           sigma <- c(i, j, 1)
           
           dif <- Dif1(x11, ssm, data, sigma)
           
           Difference <- c(Difference, dif)
           
           index <- rbind(index, sigma)
      }
   }
  
  df <- data.frame(variance=index, difference = Difference)
  return(df)
}

# loglikelihood

loglikelihood <- function(data, trend, season, sigma){
  
  n <- length(data)
  a <- 0
  for (i in 12:n)  a <- a + (sum(season[(i-11):i]))^2
  l <- -(n-11)/2 * log(sigma[1]) - 
    (n-11)/2 * log(sigma[2]) - (n-11)/2 * log(sigma[3]) -
    sum((data[-c(1:11)]-trend[-c(1:11)]-season[-c(1:10,n)])^2)/(2*sigma[1]) - 
    sum((trend[-c(1:11)]-trend[-c(1:10,n)])^2)/(2*sigma[2]) - 
    a / (2*sigma[3])
  return(l)
  
}


# logposterior

logposterior3_matrix <- function(data, c1, c2, p1, p2){
  LP <- c()
  index <- c()
   for (i in 1:15) {
     for (j in 1:15) {
         
         ssmm <- SSModel(data ~ SSMtrend(1, Q=list(j)) + 
                   SSMseasonal(12, sea.type = 'dummy', Q = 1),
                 H = i)
         ssm <- KFS(ssmm)
         
         ssm_trend <- coef(ssm, states = 'trend')
         ssm_seasonal <- -rowSums(coef(ssm, states='seasonal'))
  #      ssm_seasadj <- data[-1] - ssm_seasonal[-length(data)] # length is shorter
         sigma <- c(i, j, 1)
         
         lp <- loglikelihood(data, ssm_trend, ssm_seasonal, sigma) + logprior3(sigma, c1, c2, p1, p2)
         LP <- c(LP, lp)
         index <- rbind(index, sigma)
         
      }
   }
  df <- data.frame(variance=index, logposterior=LP)
  return(df)
}


# error for each specific situation

error3 <- function(data,i,j,p1,p2) {
  
  x11 <- seas(data, x11='')

  data_postmatrix <- logposterior3_matrix(data,i,j,p1,p2)
  
  map <- as.numeric(data_postmatrix[which.max(data_postmatrix$logposterior),][-4])
                                 
      
  ssmm <- SSModel(data ~ SSMtrend(1, Q=list(map[2])) + 
                     SSMseasonal(12, sea.type = 'dummy', Q = 1), H = map[1])
  
  ssm <- KFS(ssmm)
  
  error <- Dif1(x11,ssm,data,map)
    
  return(error) 
}
```

```{r}
# plist

plist <- sapply(Datalist, function(data,N=15){
  
  data <- ts(as.data.frame(data),start = c(2000,1),frequency = 12)

  x11 <- seas(data,x11='')
  
  data_ssmmN <- SSModel(data~SSMtrend(1,Q=list(1)) + 
                          SSMseasonal(12,sea.type = 'dummy', Q=1), H=N)
  data_ssmN <- KFS(data_ssmmN)
  data_ssmN_trend <- coef(data_ssmN, states = 'trend')
  data_ssmN_seasonal <- -rowSums(coef(data_ssmN, states = 'seasonal'))
  
  p1 <- -loglikelihood(data,data_ssmN_trend,data_ssmN_seasonal,c(N,1,1))/N
  
  
  data_ssmmN2 <- SSModel(data~SSMtrend(1,Q=list(N)) + 
                          SSMseasonal(12,sea.type = 'dummy', Q=1), H=1)
  data_ssmN2 <- KFS(data_ssmmN2)
  data_ssmN2_trend <- coef(data_ssmN2, states = 'trend')
  data_ssmN2_seasonal <- -rowSums(coef(data_ssmN2, states = 'seasonal'))
  
  p2 <- -loglikelihood(data,data_ssmN2_trend,data_ssmN2_seasonal,c(1,N,1))/N
  
  return(c(p1,p2))
  
})
```

```{r}
plist
error3(data1,1,1,plist[1,1],plist[2,1])
```


```{r}
# the most important 
# prior_gridsearch

Prior3_gridsearch <- function(datalist) {
  Error <- c()
  index <- c()
  
  for (i in 1:10) {
    for (j in 1:10) {
      error1 <- error3(datalist$data1,i,j,plist[1,1],plist[2,1])
      error2 <- error3(datalist$data2,i,j,plist[1,2],plist[2,2])
      error3 <- error3(datalist$data3,i,j,plist[1,3],plist[2,3])
      error4 <- error3(datalist$data4,i,j,plist[1,4],plist[2,4])
      error5 <- error3(datalist$data5,i,j,plist[1,5],plist[2,5])
      error6 <- error3(datalist$data6,i,j,plist[1,6],plist[2,6])
      error7 <- error3(datalist$data7,i,j,plist[1,7],plist[2,7])
      error8 <- error3(datalist$data8,i,j,plist[1,8],plist[2,8])
      error9 <- error3(datalist$data9,i,j,plist[1,9],plist[2,9])
      error0 <- error3(datalist$data0,i,j,plist[1,10],plist[2,10])
      
      error <- error1+error2+error3+error4+error5+error6+error7+error8+error9+error0
      
      Error <- c(Error, error)
      index <- rbind(index, c(i,j))
      
    }
    
  }
  
  df <- data.frame(c1=index[,1],c2=index[,2],Error=Error)
  return(df)
}

```

```

c1c2_gridsearch3 <- Prior3_gridsearch(Datalist)

write.csv(c1c2_gridsearch3,'C:\\Users\\GuoLY\\Desktop\\markdown\\MLE & MAP\\prior3_c1c2_simulationN15.csv')
```

```{r}
c1c2_gridsearch3[which.min(c1c2_gridsearch3$Error),]
```

```{r}
data1_postmatrix <- logposterior3_matrix(data1,1,6,plist[1,1],plist[2,1])
map1 <- as.numeric(data1_postmatrix[which.max(data1_postmatrix$logposterior),])

data2_postmatrix <- logposterior3_matrix(data2,1,6,plist[1,2],plist[2,2])
map2 <- as.numeric(data2_postmatrix[which.max(data2_postmatrix$logposterior),])

data3_postmatrix <- logposterior3_matrix(data3,1,6,plist[1,3],plist[2,3])
map3 <- as.numeric(data3_postmatrix[which.max(data3_postmatrix$logposterior),])

data4_postmatrix <- logposterior3_matrix(data4,1,6,plist[1,4],plist[2,4])
map4 <- as.numeric(data4_postmatrix[which.max(data4_postmatrix$logposterior),])

data5_postmatrix <- logposterior3_matrix(data5,1,6,plist[1,5],plist[2,5])
map5 <- as.numeric(data5_postmatrix[which.max(data5_postmatrix$logposterior),])

data6_postmatrix <- logposterior3_matrix(data6,1,6,plist[1,6],plist[2,6])
map6 <- as.numeric(data6_postmatrix[which.max(data6_postmatrix$logposterior),])

data7_postmatrix <- logposterior3_matrix(data7,1,6,plist[1,7],plist[2,7])
map7 <- as.numeric(data7_postmatrix[which.max(data7_postmatrix$logposterior),])

data8_postmatrix <- logposterior3_matrix(data8,1,6,plist[1,8],plist[2,8])
map8 <- as.numeric(data8_postmatrix[which.max(data8_postmatrix$logposterior),])

data9_postmatrix <- logposterior3_matrix(data9,1,6,plist[1,9],plist[2,9])
map9 <- as.numeric(data9_postmatrix[which.max(data9_postmatrix$logposterior),])

data0_postmatrix <- logposterior3_matrix(data0,1,6,plist[1,10],plist[2,10])
map0 <- as.numeric(data0_postmatrix[which.max(data0_postmatrix$logposterior),])


Map3 <- rbind(map1,map2,map3,map4,map5,map6,map7,map8,map9,map0)

Map3
```


# Prior4

$$logPrior = -c_1*k_1*\sqrt{\sigma_y^2}-c_2*k_2*\sqrt{\sigma_T^2}$$


```{r}
# logprior
logprior4 <- function(sigma,c1,c2,p1,p2){
  return(-c1*p1*sqrt(sigma[1])- c2*p2*sqrt(sigma[2]))
}
```


BTW we give a bunch of other definations below:

```{r}
# loss
Dif1 <- function(x11, ssm, data, sigma){
  
  x11_trend <- series(x11, 'd12')
  x11_seasonal <- series(x11, 'd10')
  x11_irregular <- series(x11, 'd13')
  
  ssm_trend <- coef(ssm, states = 'trend')
  ssm_seasonal <- -rowSums(coef(ssm, states='seasonal'))
  ssm_irregular <- data[-1] - ssm_trend[-1] - ssm_seasonal[-length(data)]
 
  D <-  sum((x11_irregular[-1]-ssm_irregular)^2)/sigma[1] + 
    sum((x11_trend-ssm_trend)^2)/sigma[2] + 
    sum((x11_seasonal[-1]-ssm_seasonal[-length(data)])^2)/sigma[3] 
    
  return(D)
}



# exhaustion

exhaustion1 <- function(data){
  
  Difference <- c()
  index <- c()
  
  x11 <- seas(data, x11='')
   for (i in 1:15) {
     for (j in 1:15) {
         
           ssmm <- SSModel(data ~ SSMtrend(1, Q=list(j)) + 
                     SSMseasonal(12, sea.type = 'dummy', Q = 1),
                   H = i)
           ssm <- KFS(ssmm)
           
           sigma <- c(i, j, 1)
           
           dif <- Dif1(x11, ssm, data, sigma)
           
           Difference <- c(Difference, dif)
           
           index <- rbind(index, sigma)
      }
   }
  
  df <- data.frame(variance=index, difference = Difference)
  return(df)
}

# loglikelihood

loglikelihood <- function(data, trend, season, sigma){
  
  n <- length(data)
  a <- 0
  for (i in 12:n)  a <- a + (sum(season[(i-11):i]))^2
  l <- -(n-11)/2 * log(sigma[1]) - 
    (n-11)/2 * log(sigma[2]) - (n-11)/2 * log(sigma[3]) -
    sum((data[-c(1:11)]-trend[-c(1:11)]-season[-c(1:10,n)])^2)/(2*sigma[1]) - 
    sum((trend[-c(1:11)]-trend[-c(1:10,n)])^2)/(2*sigma[2]) - 
    a / (2*sigma[3])
  return(l)
  
}


# logposterior

logposterior4_matrix <- function(data, c1, c2, p1, p2){
  LP <- c()
  index <- c()
   for (i in 1:15) {
     for (j in 1:15) {
         
         ssmm <- SSModel(data ~ SSMtrend(1, Q=list(j)) + 
                   SSMseasonal(12, sea.type = 'dummy', Q = 1),
                 H = i)
         ssm <- KFS(ssmm)
         
         ssm_trend <- coef(ssm, states = 'trend')
         ssm_seasonal <- -rowSums(coef(ssm, states='seasonal'))
  #      ssm_seasadj <- data[-1] - ssm_seasonal[-length(data)] # length is shorter
         sigma <- c(i, j, 1)
         
         lp <- loglikelihood(data, ssm_trend, ssm_seasonal, sigma) + logprior4(sigma, c1, c2, p1, p2)
         LP <- c(LP, lp)
         index <- rbind(index, sigma)
         
      }
   }
  df <- data.frame(variance=index, logposterior=LP)
  return(df)
}


# error for each specific situation

error4 <- function(data,i,j,p1,p2) {
  
  x11 <- seas(data, x11='')

  data_postmatrix <- logposterior4_matrix(data,i,j,p1,p2)
  
  map <- as.numeric(data_postmatrix[which.max(data_postmatrix$logposterior),][-4])
                                 
      
  ssmm <- SSModel(data ~ SSMtrend(1, Q=list(map[2])) + 
                     SSMseasonal(12, sea.type = 'dummy', Q = 1), H = map[1])
  
  ssm <- KFS(ssmm)
  
  error <- Dif1(x11,ssm,data,map)
    
  return(error) 
}
```

```{r}
# plist

plist <- sapply(Datalist, function(data,N=15){
  
  data <- ts(as.data.frame(data),start = c(2000,1),frequency = 12)

  x11 <- seas(data,x11='')
  
  data_ssmmN <- SSModel(data~SSMtrend(1,Q=list(1)) + 
                          SSMseasonal(12,sea.type = 'dummy', Q=1), H=N)
  data_ssmN <- KFS(data_ssmmN)
  data_ssmN_trend <- coef(data_ssmN, states = 'trend')
  data_ssmN_seasonal <- -rowSums(coef(data_ssmN, states = 'seasonal'))
  
  p1 <- -loglikelihood(data,data_ssmN_trend,data_ssmN_seasonal,c(N,1,1))/N
  
  
  data_ssmmN2 <- SSModel(data~SSMtrend(1,Q=list(N)) + 
                          SSMseasonal(12,sea.type = 'dummy', Q=1), H=1)
  data_ssmN2 <- KFS(data_ssmmN2)
  data_ssmN2_trend <- coef(data_ssmN2, states = 'trend')
  data_ssmN2_seasonal <- -rowSums(coef(data_ssmN2, states = 'seasonal'))
  
  p2 <- -loglikelihood(data,data_ssmN2_trend,data_ssmN2_seasonal,c(1,N,1))/N
  
  return(c(p1,p2))
  
})
```


```{r}
# the most important 
# prior_gridsearch

Prior4_gridsearch <- function(datalist) {
  Error <- c()
  index <- c()
  
  for (i in 1:10) {
    for (j in 1:10) {
      error1 <- error4(datalist$data1,i,j,plist[1,1],plist[2,1])
      error2 <- error4(datalist$data2,i,j,plist[1,2],plist[2,2])
      error3 <- error4(datalist$data3,i,j,plist[1,3],plist[2,3])
      error4 <- error4(datalist$data4,i,j,plist[1,4],plist[2,4])
      error5 <- error4(datalist$data5,i,j,plist[1,5],plist[2,5])
      error6 <- error4(datalist$data6,i,j,plist[1,6],plist[2,6])
      error7 <- error4(datalist$data7,i,j,plist[1,7],plist[2,7])
      error8 <- error4(datalist$data8,i,j,plist[1,8],plist[2,8])
      error9 <- error4(datalist$data9,i,j,plist[1,9],plist[2,9])
      error0 <- error4(datalist$data0,i,j,plist[1,10],plist[2,10])
      
      error <- error1+error2+error3+error4+error5+error6+error7+error8+error9+error0
      
      Error <- c(Error, error)
      index <- rbind(index, c(i,j))
      
    }
    
  }
  
  df <- data.frame(c1=index[,1],c2=index[,2],Error=Error)
  return(df)
}

```

```

c1c2_gridsearch4 <- Prior4_gridsearch(Datalist)

write.csv(c1c2_gridsearch4,'C:\\Users\\GuoLY\\Desktop\\markdown\\MLE & MAP\\prior4_c1c2_simulationN15.csv')
```

```{r}
c1c2_gridsearch4[which.min(c1c2_gridsearch4$Error),]
```





